### ISSUE TITLE
当资产过大时，页面崩溃。系统不对资产域名对应的IP进行扫描。

### ISSUE THREAD

**Issue by dd404x** [boy-hack/w12scan#10]
![image](https://user-images.githubusercontent.com/19923974/54284347-be55ec80-45da-11e9-825f-4e8c186fc580.png)
资产过大时发生这个错误
问题2
![image](https://user-images.githubusercontent.com/19923974/54284430-e04f6f00-45da-11e9-818c-de674a837f79.png)
在设置资产时，我一直使用添加子域名。建立扫描任务的时候也是，但是发现系统不对子域名对应的IP进行扫描，上图可以证明。。子域名对应IP能否自动添加进IP资产。

**Comment by boy-hack** [comment]
1. 1k多肯定是能处理的，测试过几w也能处理的，看报错信息应该是和es连接响应超时引起的，建议不要边扫描边查看（数据量大时），扫描完后再试
2. 扫描器并不会自动扫描ip，你需要将ip整理一份加入到扫描器中..

**Comment by dd404x** [comment]
好的,了解
