### ISSUE TITLE
关于搜索总是0的问题

### ISSUE THREAD

**Issue by atkiceman** [boy-hack/w12scan#11]
大佬你好 关于搜索总是0的问题 直接搜索总是为0
![image](https://user-images.githubusercontent.com/17812441/54321901-eae72400-462d-11e9-9ec7-9544580898e0.png)
创建资产后搜索还为0 不知什么原因 elastic运行正常 我的内存16G的
![image](https://user-images.githubusercontent.com/17812441/54321915-f8041300-462d-11e9-8974-1440cc7db5eb.png)
第二个问题就是 拜读了您的在线部署 但我修改配置文件后 站点就无法访问了 求您解答 谢谢
![image](https://user-images.githubusercontent.com/17812441/54322004-68129900-462e-11e9-9b37-83de0b63ac43.png)

**Comment by boy-hack** [comment]
1. 你需要添加扫描目标
2. 参见https://github.com/boy-hack/w12scan/issues/9
