### ISSUE TITLE
关于启动失败的问题

### ISSUE THREAD

**Issue by like98k** [boy-hack/w12scan#12]
```
git clone https://github.com/boy-hack/w12scan
cd w12scan
docker-compose up -d
```
根据以上命令部署时，docker启动的时候爆下面的错误
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
```
将docker-compose.yml中的dockerversion改为2之后可以正常启动，但是访问访问为503.

**Comment by boy-hack** [comment]
https://github.com/boy-hack/w12scan/issues/9

**Comment by Hotsunrize** [comment]
刚刚部署上去，准备好好看看楼主的代码，学习一波py（ps：windows下部署docker有个小坑！）
部署需要4G的内存，不一定要在vps的服务器上，在本机（我的笔记本16G就足够了）就ok了---
不过遇到了一个问题w12scan_web启动失败
<pre>
8dca7c4930be        w12scan_web                     "/opt/w12scan/docker…"   7 seconds ago       Exited (1) 5 seconds ago
</pre>
看了下logs
<pre>
`PS C:\Users\Administrator\PycharmProjects\w12scan> docker logs 8dca7c4930be
standard_init_linux.go:207: exec user process caused "no such file or directory"`
</pre>

因为windows上git pull的代码，w12scan\dockerconf\start.sh的脚本格式是dos的，需要转换下,我是上传的linux服务器，用dos2unix转换的，转换完替换windows上的脚本，docker rmi之前构建的镜像，再一次运行docker-compose up就ok了

**Comment by Hotsunrize** [comment]
老哥有交流群吗，我能加下吗，进去学习:>

**Comment by scx131** [comment]
docker api怎么更新？求教
