### ISSUE TITLE
怎么实现分布式部署？

### ISSUE THREAD

**Issue by line2222** [boy-hack/w12scan#13]
大牛你好，请问下分布式部署要怎么配置？我想要多部署几个client节点,在web端运行节点那一栏一直是空的，看不到运行节点的状态。

**Comment by boy-hack** [comment]
https://github.com/boy-hack/w12scan/blob/master/doc/deployment.md  希望这可以帮到你

**Comment by line2222** [comment]
非常感谢~~，已经启动了3个节点了，但是展现扫描节点的运行状态那一项，还是空的，但是这东西真的很不错！！
![image](https://user-images.githubusercontent.com/18050686/54730852-0d48e680-4bc6-11e9-8874-093d1d2579ce.png)

**Comment by boy-hack** [comment]
@line2222 进入到redis，`keys *`看下redis里面有数据没

**Comment by line2222** [comment]
@boy-hack  有数据

**Comment by boy-hack** [comment]
首先确保在client上能访问到redis，如果redis有数据将client重启一下应该就能出现。
