### ISSUE TITLE
创建任务后没有反应

### ISSUE THREAD

**Issue by atkiceman** [boy-hack/w12scan#14]
创建任务后从上午9点到下午3点没有扫描的迹象 一直保持图中的状态 这是为什么？
![QQ截图20190321143905](https://user-images.githubusercontent.com/17812441/54736678-3d54b180-4be7-11e9-8aa1-a8646b96f7f6.png)

**Comment by boy-hack** [comment]
1. 扫描目标是什么，大约多少个
2. docker logs 查看client的日志，将日志信息贴出来看下

**Comment by atkiceman** [comment]
又试了一次 这次又有反映了..上午是添加了200多个 这次就4 50个可以了 不知道是不是太多的缘故

**Comment by atkiceman** [comment]
还有一个问题 如何重复添加 上次添加的没有扫描完全 这次在添加就无法添加了
![image](https://user-images.githubusercontent.com/17812441/54737860-c5898580-4bec-11e9-8aab-36f78eec7c1d.png)
就像图中一样 没有success

**Comment by Hotsunrize** [comment]
> 还有一个问题 如何重复添加 上次添加的没有扫描完全 这次在添加就无法添加了
> ![image](https://user-images.githubusercontent.com/17812441/54737860-c5898580-4bec-11e9-8aab-36f78eec7c1d.png)
> 就像图中一样 没有success

你不贴log，谁能知道什么问题？上下文都没有，就截个结果，我觉得你还是自己看看代码debug下吧

**Comment by boy-hack** [comment]
@atkiceman 添加后的目标会自动去重，尝试删除client和redis重新启动吧，另外400多个是绝对可以扫描的，测试过添加4000+任务，可能是你添加的目标有太多访问超时的，这个最好先进行一次筛选再加入扫描目标

**Comment by atkiceman** [comment]
@boy-hack 明白了 谢谢 那重复添加操作我就重启redis和flushall了
