### ISSUE TITLE
资产过多，在查看时会报错

### ISSUE THREAD

**Issue by HongLuDianXue** [boy-hack/w12scan#15]
像这样：
<img width="963" alt="图片" src="https://user-images.githubusercontent.com/29145678/54889664-b5212580-4ee0-11e9-98a1-e65cb2f66911.png">

删除重新部署了几次仍然存在同样的问题。
经过测试，在新建资产那里添加过多域名（1400+）会出现这样的问题，域名少的时候正常。

**Comment by boy-hack** [comment]
refer:https://github.com/boy-hack/w12scan/issues/10
> 不要边扫描边搜索，elastisearch在插入数据时会作分析，分词等等操作（此时效率不高），如果在此时搜索可能会返回503，建议扫描完毕后在进行搜索。(后期会使用数据迁移解决)

**Comment by HongLuDianXue** [comment]
你好，已经过了一天了，但是它还是这样子，而且扫描似乎没有开始。
这是我的环境地址，请问可以帮我看一下是否正常吗？http://108.61.82.28:8000/
非常感谢！

**Comment by boy-hack** [comment]
@HongLuDianXue 任务添加在新建任务那里，资产管理多用 `*.xxx.com`这样的通配符。具体看演示视频

**Comment by HongLuDianXue** [comment]
太棒了，我已经明白怎么使用了！真是了不起的项目！

**Comment by hack2012** [comment]
IP地址过多同样会出问题。
