### ISSUE TITLE
没办法运行

### ISSUE THREAD

**Issue by gzSleet** [boy-hack/w12scan#17]
按照github文档 启动后：
![image](https://user-images.githubusercontent.com/29922543/55547258-80447800-5703-11e9-9526-0d201d67d956.png)
但是访问8000端口直接拒绝连接！不知道是哪里的问题！

**Comment by boy-hack** [comment]
你的电脑配置是多大，Elasticsearch一直在重启，可能是配置不够

**Comment by gzSleet** [comment]
好吧 vps只有两个G 太吃内存了！

boyhack <notifications@github.com> 于2019年4月4日周四 下午6:28写道：

**Comment by gzSleet** [comment]
最近也再写相关工具，想知道你的CDN判断和绕过CDN获取真实IP是怎么实现的！？

郭哲 <gz54321.a@gmail.com> 于2019年4月5日周五 上午10:15写道：

**Comment by boy-hack** [comment]
新的修改让w12scan能够支持更小的内存了，在docker-compose可以设置elasticsearch的内存容量，现在默认是512M，想支持更小内存可以使用128M，在1G1H机器上测试成功

**Comment by xinghang5029** [comment]
我用docker-compose up -d启动后，发现只启动了三个容器，w12scan_web没启动成功。请问有可能是什么问题，错误日志如下：
![image](https://user-images.githubusercontent.com/26645207/57896858-68751d80-7885-11e9-87a1-66360d720df6.png)

![image](https://user-images.githubusercontent.com/26645207/57896865-70cd5880-7885-11e9-95a9-58cf59bec94e.png)

**Comment by boy-hack** [comment]
> 我用docker-compose up -d启动后，发现只启动了三个容器，w12scan_web没启动成功。请问有可能是什么问题，错误日志如下：
> ![image](https://user-images.githubusercontent.com/26645207/57896858-68751d80-7885-11e9-87a1-66360d720df6.png)
> 
> ![image](https://user-images.githubusercontent.com/26645207/57896865-70cd5880-7885-11e9-95a9-58cf59bec94e.png)
https://github.com/w-digital-scanner/w12scan/issues/12

**Comment by scx131** [comment]
> > 我用docker-compose up -d启动后，发现只启动了三个容器，w12scan_web没启动成功。请问有可能是什么问题，错误日志如下：
> > ![image](https://user-images.githubusercontent.com/26645207/57896858-68751d80-7885-11e9-87a1-66360d720df6.png)
> > ![image](https://user-images.githubusercontent.com/26645207/57896865-70cd5880-7885-11e9-95a9-58cf59bec94e.png)
> > #12

我也是一样的问题

**Comment by scx131** [comment]
> > 我用docker-compose up -d启动后，发现只启动了三个容器，w12scan_web没启动成功。请问有可能是什么问题，错误日志如下：
> > ![image](https://user-images.githubusercontent.com/26645207/57896858-68751d80-7885-11e9-87a1-66360d720df6.png)
> > ![image](https://user-images.githubusercontent.com/26645207/57896865-70cd5880-7885-11e9-95a9-58cf59bec94e.png)
> > #12

请问你解决了吗？

**Comment by xinghang5029** [comment]
你好，我当时解决的办法是按照如下方式进行的：




xinghang5029@163.com
 
发件人： 清水
发送时间： 2019-08-02 18:10
收件人： w-digital-scanner/w12scan
抄送： xinghang5029; Comment
主题： Re: [w-digital-scanner/w12scan] 没办法运行 (#17)
我用docker-compose up -d启动后，发现只启动了三个容器，w12scan_web没启动成功。请问有可能是什么问题，错误日志如下：


#12
我也是一样的问题

**Comment by scx131** [comment]
> 你好，我当时解决的办法是按照如下方式进行的： xinghang5029@163.com 发件人： 清水 发送时间： 2019-08-02 18:10 收件人： w-digital-scanner/w12scan 抄送： xinghang5029; Comment 主题： Re: [w-digital-scanner/w12scan] 没办法运行 (#17) 我用docker-compose up -d启动后，发现只启动了三个容器，w12scan_web没启动成功。请问有可能是什么问题，错误日志如下： #12 我也是一样的问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

？？？？

**Comment by qiudaxia134** [comment]
> 按照github文档 启动后：
> ![image](https://user-images.githubusercontent.com/29922543/55547258-80447800-5703-11e9-9526-0d201d67d956.png)
> 但是访问8000端口直接拒绝连接！不知道是哪里的问题！

一样
