### ISSUE TITLE
自己搭建的es

### ISSUE THREAD

**Issue by dumpload** [boy-hack/w12scan#18]
w12scan-master/pipeline/elastic.py
PUT http://127.0.0.1:9200/w12scan/_mapping/domains [status:400 request:0.006s]
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Rejecting mapping update to [w12scan] as the final mapping would have more than 1 type: [domains, ips]')

**Comment by dumpload** [comment]
w12scan-master/pipeline/elastic.py
PUT http://127.0.0.1:9200/w12scan/_mapping/domains [status:400 request:0.006s]
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Rejecting mapping update to [w12scan] as the final mapping would have more than 1 type: [domains, ips]')

**Comment by boy-hack** [comment]
es版本是多少？尝试一下5.6版本？
