### ISSUE TITLE
redis  启动不了

### ISSUE THREAD

**Issue by Th4ck-Team** [boy-hack/w12scan#73]
Starting web_redis_1 ... 
Starting web_redis_1 ... error

ERROR: for web_redis_1  Cannot start service redis: driver failed programming external connectivity on endpoint web_redis_1 (ee730e269db02eeb65246e517c897a64ede871571ac99eae19edd822a6d6bccc): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in use

**Comment by boy-hack** [comment]
address already in use
