### ISSUE TITLE
502错误

### ISSUE THREAD

**Issue by dd404x** [boy-hack/w12scan#9]
![image](https://user-images.githubusercontent.com/19923974/54086245-aab04900-4382-11e9-9cd6-d2f0810132b5.png)

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/54094984-b2eaa180-43df-11e9-99ce-82f7200fd7b7.png)
现在没有502错误了，但是8000端口仍然无法打开，我发现elaticsearch容器一直处于重启状态

**Comment by dd404x** [comment]
我查了查，发现应该是内存不足问题，请问楼主用的什么主机，多大内存

**Comment by muYoz** [comment]
上周搭建环境，也是出现502错误，可否告知一下环境？
实验机器：
Ubuntu18.04
4核cpu
16G内存
python3.6.7

![QQ截图20190311095403](https://user-images.githubusercontent.com/24564618/54095722-a700de80-43e3-11e9-92c7-893b35c9393f.jpg)

![QQ截图20190311095500](https://user-images.githubusercontent.com/24564618/54095749-c26be980-43e3-11e9-806b-66a17cd573b7.jpg)

**Comment by dd404x** [comment]
@muYoz 我通过使用docker exec -it [id] /bin/bash 排查，发现当进入w12scan_web时提示配置文件缩进错误，你可以使用这个命令对各个已启动的容器进行错误排查。

**Comment by boy-hack** [comment]
@dd404x  先单独开启elasticsearch容器，查看日志问题，实在不行就使用elasticsearch云服务吧
@muYoz 16G内存应该是够的，用docker logs查看一下日志问题吧

**Comment by dd404x** [comment]
@boy-hack Ok，我使用云服务尝试下

**Comment by muYoz** [comment]
> @muYoz我通过使用docker exec -it [id] / bin / bash排查，发现当进入w12scan_web时提示配置文件缩进错误，你可以使用这个命令对各个已启动的容器进行错误排查。

感谢！进去容器，python main.py 发现是Django未安装。OK啦！

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/54098460-af5f1680-43ef-11e9-827c-8a067b860808.png)
![image](https://user-images.githubusercontent.com/19923974/54098563-1977bb80-43f0-11e9-8b34-b937d45b1db0.png)
![image](https://user-images.githubusercontent.com/19923974/54098961-e9c9b300-43f1-11e9-87b3-85b88ea047ba.png)

我使用阿里云服务，这样修改配置文件后，仍然无法访问 @boy-hack ，我的修改有问题吗？

**Comment by boy-hack** [comment]
> ![image](https://user-images.githubusercontent.com/19923974/54098460-af5f1680-43ef-11e9-827c-8a067b860808.png)
> ![image](https://user-images.githubusercontent.com/19923974/54098563-1977bb80-43f0-11e9-8b34-b937d45b1db0.png)
> ![image](https://user-images.githubusercontent.com/19923974/54098961-e9c9b300-43f1-11e9-87b3-85b88ea047ba.png)
> 
> 我使用阿里云服务，这样修改配置文件后，仍然无法访问 @boy-hack ，我的修改有问题吗？

1. 在`config.py`中修改 `ELASTICSEARCH_AUTH = ('elastic','password')`
2. 修改docker-compose.yml web的elasticsearch host
3. 删除原来的镜像重新`docker-compose up -d`

你好像第一步写错了，elasticsearch认证需要用户名和密码，如果还是出错请查看`docker-compose logs`信息

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/54101114-dcfe8c80-43fc-11e9-92f5-7cfc70da178f.png)
已经成功运行，非常感谢
